In [46]:
import numpy as np
import pandas as pd
import matplotlib as plt
%matplotlib inline

In [47]:
movie=pd.read_csv('movies_metadata_modified.csv')

In [48]:
movie=movie[['id','original_title','original_language','adult']]
movie.head(2)

id        original_title original_language  adult
0   2                 Ariel                fi  False
1   3  Varjoja paratiisissa                fi  False

In [50]:
movie.iloc[3000:9000]

id                      original_title original_language  adult
3000   8867                        The Punisher                en  False
3001   8868     Astérix et la surprise de César                fr  False
3002   8869                 Eight Legged Freaks                en  False
3003   8870                          Red Planet                en  False
3004   8871      How the Grinch Stole Christmas                en  False
3005   8872                       Wayne's World                en  False
3006   8873                     Wayne's World 2                en  False
3007   8874            My Best Friend's Wedding                en  False
3008   8875                        Timber Falls                en  False
3009   8879                          Pale Rider                en  False
3010   8880                       Che: Part Two                en  False
3011   8881                       Che: Part One                en  False
3012   8882                             Gomorra                it  False
3013   8883                  Flammen & Citronen                da  False
3014   8884                            Franklyn                en  False
3015   8885                      Vals Im Bashir                he  False
3016   8886                    Palermo Shooting                de  False
3017   8888                  Im Winter ein Jahr                de  False
3018   8892                    Un Conte de Noël                fr  False
3019   8893  C'est dur d'être aimé par des cons                fr  False
3020   8895                           Adoration                en  False
3021   8896                               Delta                hu  False
3022   8897              La Frontière de l'aube                en  False
3023   8898                 La mujer sin cabeza                es  False
3024   8899                 Le Silence de Lorna                fr  False
3025   8900                             Leonera                es  False
3026   8902                      Linha de Passe                pt  False
3027   8904                              Serbis                tl  False
3028   8905                           Üç maymun                tr  False
3029   8906                             Wolke 9                de  False
...     ...                                 ...               ...    ...
8970  19765                              Želary                cs  False
8971  19766                  Inspector Gadget 2                en  False
8972  19792            Firestarter 2: Rekindled                en  False
8973  19794                         Labor Pains                en  False
8974  19797                        I Think I Do                en  False
8975  19803                       Underclassman                en  False
8976  19809                     Copper Mountain                en  False
8977  19812      Far til fire - gi'r aldrig op!                da  False
8978  19819                          Blue Chips                en  False
8979  19823                    Dolan's Cadillac                en  False
8980  19824           Van Wilder: Freshman Year                en  False
8981  19827                         The In-Laws                en  False
8982  19828                        10 Attitudes                en  False
8983  19829                  Ninja Cheerleaders                en  False
8984  19833                         In the Loop                en  False
8985  19837                           Beer Wars                en  False
8986  19840             I Love You, Beth Cooper                en  False
8987  19844                      Kiss the Bride                en  False
8988  19846                       The Interview                en  False
8989  19848                    The Players Club                en  False
8990  19850                          Breast Men                en  False
8991  19851                        Grey Gardens                en  False
8992  19855                             The War                en  

In [5]:
ratings=pd.read_csv('ratings_small.csv',error_bad_lines=False,encoding='latin-1')

In [6]:
ratings.rename(columns={'movieId':'id'},inplace=True)

In [7]:
count_user=ratings['userId'].value_counts()
len(count_user)

671

In [8]:
rating=ratings[ratings['userId'].isin(count_user[count_user>100].index)]

In [9]:
len(rating)

80487

In [10]:
movie_with_rating=rating.merge(movie,on='id')

In [11]:
movie_with_rating.shape

(34640, 7)

In [12]:
movie_num_ratings=movie_with_rating.groupby('original_title')['rating'].agg('count').sort_values(ascending=False).reset_index().rename(columns={'rating':'num_rating'})

In [13]:
movie_with_rating_numrating=movie_with_rating.merge(movie_num_ratings,on='original_title')

In [14]:
min_num_rating=movie_with_rating_numrating[movie_with_rating_numrating['num_rating']>1000]

In [15]:
movie_with_rating_numrating.shape

(34640, 8)

In [16]:
movie_with_rating_numrating.drop_duplicates(['userId','original_title'],inplace=True)

In [17]:
len(movie_with_rating_numrating)#my srk has new name movie_with_rating_numrating

34496

In [18]:
pivot_table=movie_with_rating_numrating.pivot_table(index='original_title',columns='userId',values='rating').fillna(0)

In [19]:
pivot_table.shape

(2727, 258)

In [20]:
from scipy.sparse import csr_matrix
csr=csr_matrix(pivot_table)

In [21]:
type(csr)

scipy.sparse.csr.csr_matrix

In [22]:
from sklearn.neighbors import NearestNeighbors
nn=NearestNeighbors(metric='cosine',algorithm='brute')

In [23]:
nn.fit(csr)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
         metric_params=None, n_jobs=1, n_neighbors=5, p=2, radius=1.0)

In [25]:
distances,movie=nn.kneighbors(pivot_table.iloc[0,:].values.reshape(1,258), n_neighbors=6)

In [26]:
movie=movie.ravel()
movie

array([   0, 1636, 2063, 1788,  998, 1216], dtype=int64)

In [27]:
for i in movie:
    print(pivot_table.index[i])

!Women Art Revolution
Premium Rush
The Eleventh Victim
Shadow Run
In the Name of the Father
Le fil


In [28]:
pivot_table.index=='Jarhead'

array([False, False, False, ..., False, False, False])

In [29]:
np.where(pivot_table.index=='Jarhead')

(array([1036], dtype=int64),)

In [30]:
np.where(pivot_table.index=='Jarhead')[0][0]

1036

In [35]:
def suggest(name):
    movie_id=np.where(pivot_table.index==name)[0][0]
    distance,movie=nn.kneighbors(pivot_table.iloc[movie_id,:].values.reshape(1,258),n_neighbors=10)
    for i in movie.ravel():
        print(pivot_table.index[i])

In [54]:
name=input('Enter a movie name')
suggest(name)

Enter a movie nameJarhead
Jarhead
Men in Black II
La science des rêves
Sleepless in Seattle
Edward Scissorhands
Los Olvidados
Terminator 3: Rise of the Machines
Lonely Hearts
座頭市
The Million Dollar Hotel
